### ISSUE TITLE
 Needs update # of projected species

### ISSUE THREAD

**Issue by naithanis** [PlantReactome/production-issues#10]
http://plantreactomedev.oicr.on.ca/download/

"Current Release (MySQL, aligned with Gramene Rel.43) - contains rice pathways and *_projections to 33 *_other plant species "

Needs update # of projected species

**Comment by jaiswalp** [comment]
Justin do you want me to change it on this page or when you move to a potential live site.

**Comment by preecej** [comment]
When we migrate, we can make the small updates directly to the Production site.

Let's just handle these small content changes directly on the live site the day before release; there aren't that many. If there are any "large" content changes -- like the stats page -- I prefer to stage them in Test and then copy-paste (or export/import) to Prod from one Wordpress instance to the other.

**Comment by preecej** [comment]
I updated the "Downloads" page in Test, since it is not a WP page. I will migrate it during the release window with the rest of the software and data.

I have added a new data dump of projected gene products - listed by pathway and reaction - indexed to curated Oryza sativa gene products (tab-delimited): http://plantreactomedev.oicr.on.ca/download/pathways_reactions_gene_projections.tab

**Comment by preecej** [comment]
i updated the quoted number of species as well: http://plantreactomedev.oicr.on.ca/download/
