### ISSUE TITLE
Suberin pathway missing gene products (and reactions) in projections

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/production-issues#2]
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#DIAGRAM=1119418&PATH=2894885,2744345,2744344&DTAB=MT

the gene on the left hand side sub pathway for 'oleate omega-hydroxylase' 

the rice genes Os01g0803900 and Os01g0804400 have A. thaliana homologs AT1G34540 and  
AT3G56630 that are both above our threshold. And they are mising from the A. thaliana projections
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=8950633&DIAGRAM=8955726&PATH=8955592,8955591,8955607&DTAB=MT

In fact these rice genes have homologs for O. nivara and indica that's 100% identical (http://ensembl.gramene.org/Oryza_sativa/Gene/Compara_Ortholog?db=core;g=OS01G0804400;r=1:34115002-34116757;t=OS01T0804400-01) and we are still  missing the projected reaction
http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=9122308&DIAGRAM=9126319&PATH=9126183,9126182,9126199&DTAB=MT

**Comment by preecej** [comment]
The source of the issue is that our pre-projection mapping files are generated using the assumption that we only want to work with LOCs.

The solution that I'm going to try is two-fold:
1. Expand the RGP dump from our slice to include instances with a UniProt id + an Os id in a geneName slot, not just UniProt id + LOC id
2. Provide conditions in the inparanoid script to accept Os::UniProt mappings when provided, assuming that they don't duplicate an existing LOC::UniProt mapping. (When we convert to Os wholesale (right after release), this code will be changed to only work with Os::UniProt.) This should generate new Reactome inference mappings for curated rice pathways that only reference Os and not LOC.

**Comment by preecej** [comment]
1. Expanded RGP dump generates an add'l 111 gene products, inc. those associated with this ticket.
2. Working on it.

**Comment by preecej** [comment]
1. Progress. After some serious software revision, I have expanded the mapping to include newly curated Os RGPs, and I can confirm that the AT genes in this ticket are carried forward into At and Zm projections (along with all other Ensembl species, where thresholds are met).

Unfortunately, this improvement also requires a more complex download of inparanoid cluster entries (Our pipeline is affected in multiple places by the intermingling of LOC and Os ids). I can either just run an expanded mapping set for Ensembl only (inc At and Zm), or extend to Inparanoid as well.

I will spend 2-3 hrs trying to extend to inparanoid, but if it doesn't get anywhere tomorrow morning, we'll move forward with our existing set of inparanoid projections and an expanded set of ensembl projections.

I can't wait to switch over to Os only after this release, and get rid of this unnecessary LOC mapping.   <:/

**Comment by preecej** [comment]
We're going to go with expanded Ensembl projections (with add'l Os IDs) this release -- which will ensure more projection hits for critical species like At and Zm. We won't lose any Inparanoid projections that we had previously, but we won't gain any for curated Os RGPs, either. Next release, this issue will resolve itself once we're converted to Os IDs across the board.

**Comment by preecej** [comment]
Fixed and deployed to Test env. Please verify and close:

http://plantreactomedev.oicr.on.ca/PathwayBrowser/#SPECIES=8951557&DIAGRAM=8957007&ID=8954963&PATH=8956872,8956871,8956887&DTAB=MT
