### ISSUE TITLE
Browser compatibility problems for FF and IE: pathway browser, species comparison tool

### ISSUE THREAD

**Issue by jaiswalp** [PlantReactome/production-issues#9]
When I compared O. sativa with prunus, i get the table, and sometimes it goes to the pathway view as well wit yellow and blue color...but after a while the colors disappear and a text box says..

'There is no result associated with the provided token (in the url) from a previous analysis'

after this all the analysis data disappears

**Comment by jaiswalp** [comment]
tried again with Ostreococcus lucimarinus, it shows data in table and then pops a dialogue...

'Your result may have been deleted due to a new content release.
Please submit your data again to obtain results from the latest version of our database'

**Comment by jaiswalp** [comment]
same with A. thaliana and Zea mays.

**Comment by preecej** [comment]
Just attempted with all four species you mentioned. Works here on Chome/Linux. Try a new browser session and let me know.

**Comment by jaiswalp** [comment]
See if this is not a memory allocation issue for archiving the analysis data!

**Comment by jaiswalp** [comment]
Works on Chrome. Firefox continues to behave as mentioned before and IE simply failed to open the browser. BTW I am on Windows

**Comment by preecej** [comment]
As it seems this is a browser/OS compat issue, perhaps we should involve the larger Reactome group. IMHO, they will probably not be inclined to address a support issue for Reactome 3.0. The more important question is whether any of this appears on Reacotme 3.1, since that is where we're going ASAP. Just curious: can you load reactome.org on IE and Firefox and try browsing and species comparison?

**Comment by jaiswalp** [comment]
IE hangs on reactome.org pathway browser. FF works.

**Comment by preecej** [comment]
No explicit mention of IE compat that I can find on reactome.org.

@deustp01 : What are the current browser compatibility claims for human Reactome 3.1? Were they different for 3.0?

@jaiswalp : What version of Windows and IE are you using?

**Comment by deustp01** [comment]
For whatever it's worth, I don't recall an issue like this with the previous version of the pathway browser, and we routinely check at least Firefox and IE on both Windows and Mac machines.

**Comment by jaiswalp** [comment]
using IE 11

On 3/28/2016 1:18 PM, Justin Preece wrote:

> No explicit mention of IE compat that I can find on reactome.org.
> 
> @deustp01 https://github.com/deustp01 : What are the current browser 
> compatibility claims for human Reactome 3.1? Were they different for 3.0?
> 
> @jaiswalp https://github.com/jaiswalp : What version of Windows and 
> IE are you using?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/PlantReactome/temp-issues/issues/9#issuecomment-202565046

## 

Pankaj Jaiswal, PhD
Associate Professor
Dept. of Botany and Plant Pathology
2082 Cordley Hall
Oregon State University
Corvallis, OR, 97331
USA

Ph.: +1-541-737-8471
Fax: +1-541-737-3573
email: jaiswalp@oregonstate.edu
Web: http://jaiswallab.cgrb.oregonstate.edu/

**Comment by deustp01** [comment]
Above, Pankaj said:
"tried again with Ostreococcus lucimarinus, it shows data in table and then pops a dialogue...
'Your result may have been deleted due to a new content release.
Please submit your data again to obtain results from the latest version of our database' "

I've never encountered this one. here's a wild-guess diagnosis. The tool assigns a unique token to every analysis it does and saves the results, associated with that token, even after the user leaves the site. The user can come back later and use the token to retrieve the results (also supports various RESTful API operations). The results are saved for seven days or until our results-storage quota is exceeded, whichever is longer. Now the wild guess: would it make sense to dump old results when a new data set is released, and could you somehow be colliding with that?

**Comment by preecej** [comment]
It's possible. I will clear the server cache that holds those results.

**Comment by deustp01** [comment]
IE 11 - that could be a problem; I'm not sure we ever tried to run the old system on anything beyond IE 10 - I certainly didn't and the developers may all use Mac or Linux machines.

**Comment by preecej** [comment]
Browser compat for an older Reactome is going to be a snipe hunt. I suggest we just get on Reactome 3.1 / concurrent ASAP and then see where we stand.

**Comment by jaiswalp** [comment]
On 3/28/2016 1:24 PM, deustp01 wrote:

> Above, Pankaj said:
> "tried again with Ostreococcus lucimarinus, it shows data in table and 
> then pops a dialogue...
> 'Your result may have been deleted due to a new content release.
> Please submit your data again to obtain results from the latest 
> version of our database' "

i don't get this error on Chrome. So probably it is not a data archive 
associated.

pankaj

**Comment by preecej** [comment]
then another guess: it could also be a browser-cache on the client end.

@jaiswalp you could empty your FF cache and see what happens.

**Comment by jaiswalp** [comment]
After clearing the FF cache it still says
'There is no result associated with the provided token (in the url) from 
a previous analysis'

**Comment by preecej** [comment]
Esp. in light of Peter's comments, I recommend that we get on 3.1 for next release and see how many of these issues resolve themselves.

**Comment by preecej** [comment]
https://github.com/reactome/PathwayBrowser/blob/master/pom.xml#L16

I think you have there 2.6.1

Try if it works with 2.7.0
- Antonio
